nome = str (input('Digite seu nome: '))
sobrenome = str (input('Digite seu sobrenome: '))
idade = int (input('Digite sua idade: '))
ano_nascimento = int (input('Digite seu ano de nascimento: '))
altura = float (input('Digite sual altura ex: 1.78: '))
print()
print()
print('Nome:', nome, sobrenome)
print('Sua idade é,', + idade)
print('Seu ano de nascimento é,', + ano_nascimento)
print('Sua altura é,', + altura)
print('Voce é maior de idade = ', idade >= 18)
print('Esses são seus dados.') 